name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Debug file paths
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files in project directory:"
          ls -R

      - name: Run Playwright tests
        run: npx playwright test
